ak_blog:
    resource: "@AKBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


square_number:
  path: /square/{number}
  defaults:
      _controller: AppBundle:Square:squareNumber